runtime: ruby27
entrypoint: bundle exec ruby app.rb
instance_class: F2

handlers:
- url: /
  static_files: public/index.html
  upload: /
  secure: always
- url: /(.*\.xml)
  mime_type: application/xml
  static_files: public/\1
  upload: public/(.*\.xml)
- url: /favicon.ico
  static_files: public/favicon.ico
  expiration: "1d"
  secure: always
  upload: public/favicon.ico
- url: /404.html
  static_files: public/404.html
  upload: /404.html
  secure: always
- url: /css
  static_dir: public/css
  secure: always
- url: /js
  static_dir: public/js
  secure: always
- url: /dist
  static_dir: public/dist
  secure: always
- url: /images
  static_dir: public/images
  secure: always
  expiration: "12h"
- url: /(.*)/$
  static_files: public/\1/index.html
  upload: .*\.html$
  secure: always
- url: /.*
  script: auto
  secure: always
