runtime: go
api_version: go1.8
threadsafe: true

default_expiration: "10m"

handlers:
- url: /
  static_files: public/index.html
  upload: /
  secure: always
- url: /
  static_files: public/404.html
  upload: /404.html
  secure: always
- url: /css
  static_dir: public/css
  secure: always
- url: /fonts
  static_dir: public/fonts
  secure: always
- url: /js
  static_dir: public/js
  secure: always
- url: /img
  static_dir: public/img
  secure: always
- url: /dist
  static_dir: public/dist
  secure: always
- url: /images
  static_dir: public/images
  secure: always
- url: /(.*)/$
  static_files: public/\1/index.html
  upload: .*\.html$
  secure: always
- url: /.*
  script: _go_app
  secure: always