runtime: go
api_version: go1.8
threadsafe: true

default_expiration: "10m"

handlers:
- url: /
  static_files: public/index.html
  upload: /
  secure: always
- url: /(.*\.xml)
  mime_type: application/xml
  static_files: public/\1
  upload: public/(.*\.xml)
- url: /404.html
  static_files: public/404.html
  upload: /404.html
  secure: always
- url: /styles
  static_dir: public/styles
  secure: always
- url: /fonts
  static_dir: public/fonts
  secure: always
- url: /js
  static_dir: public/js
  secure: always
- url: /img
  static_dir: public/img
  secure: always
- url: /dist
  static_dir: public/dist
  secure: always
- url: /images
  static_dir: public/images
  secure: always
- url: /(.*)/$
  static_files: public/\1/index.html
  upload: .*\.html$
  secure: always
- url: /.*
  script: _go_app
  secure: always

skip_files: |
  ^(.*/)?(
  (archetypes/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (config\.yaml)|
  (cloudbuild\.yaml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (manage\.py)|
  (README\.md)|
  (LICENSE)|
  (content\/.*)|
  (data\/.*)|
  (static\/.*)|
  (layouts\/.*)|
  (\.git\/.*)|
  (\.gitignore)|
  )$