steps:
- name: ubuntu
  id: mkdirSophie
  args: ['mkdir', '-p', 'static/images/sophie']
- name: gcr.io/cloud-builders/gsutil
  id: cat
  args: ['-m', 'cp', '-r', 'gs://sophie-pictures/*.jpg', 'static/images/sophie']
  waitFor:
  - mkdirSophie
- name: gcr.io/cloud-builders/git
  id: submoduleInit
  args: ['submodule', 'init']
- name: gcr.io/cloud-builders/git
  id: submoduleUpdate
  args: ['submodule', 'update']
  waitFor:
  - submoduleInit
- name: ubuntu
  id: mkdirResources
  args: ['mkdir', '-p', 'resources']
- name: cibuilds/hugo:0.64.0
  args: ['hugo', '-b', '$_BASE_URL']
  id: hugo
  env:
  - HUGO_ENV=production
  waitFor:
  - cat
  - mkdirResources
  - submoduleUpdate
- name: gcr.io/cloud-builders/gcloud
  args: ['app', 'deploy', '--quiet', '--project', '$PROJECT_ID', app.yaml]
  waitFor:
  - hugo