baseURL = "https://thomasmullaly.codes/"
languageCode = "en-us"
title = "Thomas Mullaly"
theme = "mainroad"
paginate = "10"
googleAnalytics = "UA-77282496-2"
disqusShortname = "thomas-mullaly-codes"

[permalinks]
  post = "/:year/:month/:day/:title/"

[Taxonomies]
  tag = "tags"
  category = "categories"

[Author]
  name = "Thomas Mullaly"
  profile = "/page/about-me/"
  avatar = "/images/me.jpg"

[Params]
  subtitle = "Ramblings of a software developer"
  shareGooglePlus = false
  dateFormat = "January 2, 2006"
  opengraph = true
  readmore = true
  post_navigation = true
  postSections = ["post"]

[Params.widgets]
  search = false
  recent_articles = true
  categories = true
  tags = true
  social_twitter = "https://twitter.com/thomas_mullaly"
  social_github = "https://github.com/thomas-mullaly"
  social_email = "thomas.mullaly@gmail.com"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about-me/"
  weight = 2