baseURL = "https://thomasmullaly.codes/"
languageCode = "en-us"
title = "Thomas's Blog"
theme = "ghostwriter"

[permalinks]
  post = "/:year/:month/:day/:title/"

[Taxonomies]
  tag = "tags"

[Author]
  name = "Thomas Mullaly"

[Params]
  twitter = "https://twitter.com/thomas_mullaly"
  github = "https://github.com/thomas-mullaly"
  email = "thomas.mullaly@gmail.com"
  shareGooglePlus = false