baseURL = "https://thomasmullaly.codes/"
languageCode = "en-us"
title = "Thomas Mullaly"
theme = "Mainroad"
paginate = "10"
googleAnalytics = "UA-77282496-2"
disqusShortname = "thomas-mullaly-codes"

[permalinks]
  post = "/:year/:month/:day/:title/"

[Taxonomies]
  tag = "tags"
  category = "categories"

[Author]
  name = "Thomas Mullaly"
  profile = "/page/about-me/"
  avatar = "/images/me.jpg"

[Params]
  subtitle = "Software Engineer"
  dateFormat = "January 2, 2006"
  opengraph = true
  readmore = true
  post_navigation = true
  postSections = ["post"]

[Params.widgets]
  recent_num = 5

[Params.sidebar]
  home = "right"
  list = "left"
  single = false
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets.social]
  twitter = "thomas_mullaly"
  github = "thomas-mullaly"
  email = "thomas.mullaly@gmail.com"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about-me/"
  weight = 2